FROM node:20-alpine AS base
WORKDIR /app

COPY package*.json ./

RUN npm install

COPY tsconfig.json ./tsconfig.json
COPY src ./src

RUN npm run build && npm prune --omit=dev

FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production

COPY --from=base /app/package.json ./package.json
COPY --from=base /app/node_modules ./node_modules
COPY --from=base /app/dist ./dist

EXPOSE 5300

CMD ["node", "dist/main.js"]

